spring:
  datasource:
    url: jdbc:mysql://localhost:3306/pokenary_db?useSSL=false&createDatabaseIfNotExist=true
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    initialization-mode: always
  sql:
    init:
      mode: always
  jpa:
    generate-ddl: true
#    defer-datasource-initialization: true
#    hibernate:
#      ddl-auto: create
#      dialect: org.hibernate.dialect.MySQLDialect
#      naming_strategy: org.hibernate.cfg.ImprovedNamingStrategy
    show-sql: true
